name: Auto Update Playlist
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Chrome and Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install selenium webdriver-manager

      - name: Run Crawl
        run: python crawl.py

      - name: Push Changes
        run: |
          git config --global user.name 'CrawlBot'
          git config --global user.email 'bot@noreply.github.com'
          git add playlist.m3u
          git commit -m "Update links via Selenium $(date)" || exit 0
          git push
